
import { ChannelType, AutomationChannel, ScheduledPost, Tenant } from '../types';

const CHANNELS: ChannelType[] = ['LinkedIn', 'X', 'Google Business', 'YouTube', 'Medium', 'Shopify'];

export const triggerAutomationRipple = async (tenantId: string): Promise<void> => {
  console.log(`Action Engine: Orchestrating Post-Onboarding Ripple for Tenant ${tenantId}`);
  
  // Simulation of parallel publisher tasks (FR-501 to FR-504)
  const initialChannels: AutomationChannel[] = CHANNELS.map(type => ({
    type,
    status: 'Pending'
  }));

  const updateTenantAutomation = (channels: AutomationChannel[], progress: number) => {
    const savedTenants = localStorage.getItem('tenants');
    if (savedTenants) {
      const tenants = JSON.parse(savedTenants);
      const updated = tenants.map((t: Tenant) => 
        t.id === tenantId 
          ? { ...t, automationWorkflow: { channels, overallProgress: progress } } 
          : t
      );
      localStorage.setItem('tenants', JSON.stringify(updated));
      // Dispatch custom event to notify components
      window.dispatchEvent(new CustomEvent('tenantUpdated', { detail: { tenantId } }));
    }
  };

  updateTenantAutomation(initialChannels, 5);

  // Parallel simulation of AI content generation and profile creation
  CHANNELS.forEach((type, index) => {
    setTimeout(() => {
      const currentChannels = JSON.parse(localStorage.getItem('tenants')!)
        .find((t: any) => t.id === tenantId).automationWorkflow.channels;
      
      const updatedChannels = currentChannels.map((c: AutomationChannel) => 
        c.type === type ? { ...c, status: 'Generating', lastAction: 'AI synthesis in progress...' } : c
      );
      
      updateTenantAutomation(updatedChannels, 10 + (index * 15));

      setTimeout(() => {
        const finalChannels = JSON.parse(localStorage.getItem('tenants')!)
          .find((t: any) => t.id === tenantId).automationWorkflow.channels;
          
        const activatedChannels = finalChannels.map((c: AutomationChannel) => 
          c.type === type ? { ...c, status: 'Active', lastAction: `Channel activated at ${new Date().toLocaleTimeString()}` } : c
        );
        
        const progress = Math.min(100, 10 + (index + 1) * 15);
        updateTenantAutomation(activatedChannels, progress);

        // Populate initial schedule if first channel activated
        if (index === 0) {
          generateInitialSchedule(tenantId);
        }
      }, 3000 + (index * 1000));
    }, 1000 + (index * 500));
  });
};

const generateInitialSchedule = (tenantId: string) => {
  const posts: ScheduledPost[] = [
    {
      id: 'sp1',
      platform: 'LinkedIn',
      title: 'Our Strategic Mission Launch',
      publishAt: new Date(Date.now() + 86400000).toISOString(),
      status: 'Scheduled',
      contentSummary: 'A high-authority article synthesized from our Core Mission statement.'
    },
    {
      id: 'sp2',
      platform: 'YouTube',
      title: 'Brand Vision Explainer (AI Processed)',
      publishAt: new Date(Date.now() + 172800000).toISOString(),
      status: 'Scheduled',
      contentSummary: 'Synthesized video reel utilizing assets from Media Hub.'
    },
    {
      id: 'sp3',
      platform: 'X',
      title: 'Market Trends Insight #1',
      publishAt: new Date(Date.now() + 43200000).toISOString(),
      status: 'Scheduled',
      contentSummary: 'Short-form analysis generated by the Market Intelligence Hub.'
    }
  ];
  localStorage.setItem(`scheduled_posts_${tenantId}`, JSON.stringify(posts));
};

export const getScheduledPosts = (tenantId: string): ScheduledPost[] => {
  const data = localStorage.getItem(`scheduled_posts_${tenantId}`);
  return data ? JSON.parse(data) : [];
};
